### ISSUE TITLE
run in background even after closing 

### ISSUE THREAD

**Issue by jithinjames916** [PurpleI2P/i2pd-android#60] opened 2023-12-02 04:01 UTC
Please add ability to run in background even if the app is closed. The notification will show if the app is running or not. This help uses from accidently closing the app. If it's already implemented please tell me how to use it.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment] 2024-04-04 11:08
duplicate of #50, implemented by #62

**Comment by nonlin-lin-chaos-order-etc-etal** [comment] 2024-07-22 00:27
@r4sas please close this

**Closed** 2024-07-25 14:20 UTC
